### ISSUE TITLE
Add MongoDB support

### ISSUE THREAD

**Issue by gimenete** [clevertech/authentication-service#4]
Supporting MongoDB would be cool. The database access is decoupled in a simple interface as can be seen here: https://github.com/clevertech/authentication-service/blob/master/src/database/knex.js A `src/database/mongo.js` adapter should be implemented with the same interface.

There should just be some ENV variables to tell the app which database engine should be used.

**Comment by callaars** [comment]
On a high level you should only provide a minimal amount of functions to the "repository", so that db adapters can be switched out easily without knowing the full extend of the application.

For example only having `create`, `edit`, `getOne` and `getAll` is enough for a db adapter, and it wouldn't have to know of "higher" layers of the applications such as "getting a user by email".

**Comment by gimenete** [comment]
I like that 👍
